title: "Francis Thelen's Weblog"

author: "Francis Thelen"

description: >
  My personal weblog, where I write about my interests, projects, and
  experiences. This is a place for me to share my thoughts and connect with
  others.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  date_format: "%b-%d-%Y"
  hide_site_feed_link: false
